name:                till
version:             0.0.1.0
github:              "gillchristian/till"
license:             MTI
author:              "Christian Gill"
maintainer:          "gillchristiang@gmail.com"
copyright:           "2019 Christian Gill"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/gillchristian/till#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
- base >= 4.7 && < 5
- process
- parsec
- optparse-applicative
- ansi-terminal
- dates >= 0.2.3.0 && < 0.3

library:
  source-dirs: src

executables:
  till:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wpartial-fields
    - -Wredundant-constraints
    - -Wmissing-export-lists
    - -fhide-source-paths
    dependencies:
    - till

tests:
  till-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wpartial-fields
    - -Wredundant-constraints
    - -Wmissing-export-lists
    - -fhide-source-paths
    dependencies:
    - till
    - hspec
